[RM-1001] Buiding UI
vxduc9999/learningVue pull request #7
Opened 2021-06-11 04:03 UTC by vxduc9999

I using flexbox to build layout, using google icons,
reset css default website
References: RM-1001

2021-06-14 18:03 UTC, phuphamphong97 requested changes
Good job Duc!
You catch up with everything quickly, the first step is pretty good.
I left some comments, hope they are useful to you.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +      <div class="left-feature">
CSS classes should be named in a consistent way. In our project we use `-` for classes name and `_` for IDs.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +        <list-feature :lists="lists"></list-feature>
```suggestion
        <ListFeature :lists="lists" />
```

See:

- [Component name casing in templates](https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended)
- [Self-closing components](https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended)

Should check for other similar components.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +        <p>Add List</p>
Although it is a placeholder for later development, it will make sense if this is a button.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +    <div class="column-layout" v-if="Object.keys(list).length !== 0">
- The class name needs to be more descriptive.
- The condition can be shortened to `v-if="Object.keys(list).length"`

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +      </div>
- We also need a `button` here, instead of a `div` with the `click` event.
- `addTask()` should be removed until it's ready for use. Check for other unused function calls.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +        v-if="Object.keys(list).length !== 0"
Duplicate logic, should consider to make it a `computed` property.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +  name: "Navigation",
Component name and file name should be the same, or at least something related.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +      lists: [
As discussed, we will to move all the data to a global store using `vue-stash`, then access it whenever we need it.
And maybe the data needs restructuring too, but we'll look at it once the global state is applied.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +  },
Component options should be rearranged. See [Component/instance options order](https://vuejs.org/v2/style-guide/#Component-instance-options-order-recommended)

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Home.vue
> +<style scoped>
We'll talk about CSS code later, it's pretty messy right now.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/ListFeature.vue
> +            <i class="material-icons" id="icons">
The `id` of an element is unique, so it is not allowed to use one id for more than one element.
Remember to use class instead of ID selector when applying styles to elements.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/ListFeature.vue
> +    all: function() {
- `all` is not a good name.
- We temporarily ignore the rest of this function, until we have the global state.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Lists.vue
> +          </span>
Should select only one between `<i>` and `<span>` for icons.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Lists.vue
> +    },
The plural name indicates it should be of type array.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Lists.vue
> +  computed: {},
Any unused lines of code should be removed.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Tasks.vue
> +          ></textarea>
Suggestion:
```
<textarea v-if="task.editing">
  // ...
</textarea >
<span v-else>
  // ...
</span>  
```

Should take care of the [Element attribute order](https://vuejs.org/v2/style-guide/#Element-attribute-order-recommended), too.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Tasks.vue
> +    },
Not a good solution. Try to think of another way to handle adding a new task.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Tasks.vue
> +      console.log(id);
```suggestion
```

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/Tasks.vue
> +    taskImportant(id) {
The function name should be a verb.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/components/TheHeader.vue
> +    },
The prop name indicates it should be of type array.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/main.js
> +  resetcss,
I'm not sure this works.

2021-06-14 18:03 UTC, phuphamphong97 commented on src/main.js
> +import resetcss from '@/css/resetCss.css'
```suggestion
import '@/css/resetCss.css'
```
`reset-css.css`, or just simply `reset.css`, is a better name. Don't use camelCase for file names.

2021-06-16 07:06 UTC, vxduc9999 commented
I close the pull request because I build the project according to the new strategy

2021-06-16 07:07 UTC, closed without merging